preprocessing:
  folders: ["UnitedNations"]
  lower_case: True
  min_words: 5
  mask_symbol: "\r"
encoding:
  word_based: False
  # if word_based True maximal number of words per statement,
  # otherwise maximal number of characters
  max_seq_len: 200
  start_token: "\t"
  end_token: "\n"
model_training:
  train: False
  model: "CharToCharBiLSTM"
  epochs: 50
  save_epochs: 50
  learning_rate: 0.1
  batch_size: 64
  num_neurons: 128
  validation_split: 0.1
load_model:
  folder: "CharToCharBiLSTM_2023-11-09_12-43"
  epoch: 50