preprocessing:
  lower_case: True
  min_words: 5
  mask_symbol: "\r"
encoding:
  word_based: False
  # if word_based True maximal number of words per statement,
  # otherwise maximal number of characters
  max_seq_len: 200
  start_token: "\t"
  end_token: "\n"
model_training:
  train: False
  model: "CharToCharLSTM"
  epochs: 20
  save_epochs: 5
  batch_size: 64
  num_neurons: 64
  validation_split: 0.1
load_model:
  folder: "CharToCharLSTM_2023-11-07_15-41"
  epoch: 20