preprocessing:
  folders: ["UnitedNations", "Wikipedia", "NationalGeographic",
            "TheNewYorkTimes", "NationalOceanicAndAtmosphericAdministration"]
  lower_case: True
  min_words: 5
  mask_symbol: "\r"
encoding:
  word_based: False
  # if word_based True maximal number of words per statement,
  # otherwise maximal number of characters
  max_seq_len: 200
  # if word_based True size of output vocabulary, otherwise
  # maximal output sequence length
  max_output: 30
  # both tokens only important for character based encoding (word based False)
  start_token: "\t"
  end_token: "\n"
model_training:
  train: False
  use_generator: True
  model: "CharToCharBiLSTM"
  epochs: 10
  # save model weights every save_epochs iterations
  save_epochs: 5
  learning_rate: 0.01
  batch_size: 64
  num_neurons: 256
load_model:
  folder: "WordvecToWordLSTM_2023-11-15_11-42"
  epoch: 20