preprocessing:
  folders: ["UnitedNations", "Wikipedia", "NationalGeographic",
            "TheNewYorkTimes", "NationalOceanicAndAtmosphericAdministration"]
  lower_case: True
  min_words: 5
  mask_symbol: "<mask>"
encoding:
  word_based: True
  # if word_based True maximal number of words per statement,
  # otherwise maximal number of characters
  max_seq_len: 30
  # if word_based True size of output vocabulary, otherwise
  # maximal output sequence length
  max_output: 3000
  # both tokens only important for character based encoding (word based False)
  start_token: "\t"
  end_token: "\n"
model_training:
  train: True
  use_generator: False
  model: "WordvecToWordLSTM"
  epochs: 50
  # save model weights every save_epochs iterations
  save_epochs: 10
  learning_rate: 0.01
  batch_size: 64
  num_neurons: 512
load_model:
  folder: "WordvecToWordLSTM_2023-11-14_17-27"
  epoch: 5