preprocessing:
  # if file already exists, read statements from it otherwise create it
  data_file: 'assembled_statements.txt'
  folders: ["UnitedNations", "Wikipedia", "NationalGeographic",
            "TheNewYorkTimes", "NationalOceanicAndAtmosphericAdministration"]
  lower_case: True
  min_words: 5
  mask_symbol: "[MASK]"
  word_tokenizer: "DistilBERT"
encoding:
  word_based: True
  # if word_based True maximal number of words per statement,
  # otherwise maximal number of characters
  max_seq_len: 30
  # if word_based True size of output vocabulary, otherwise
  # maximal output sequence length
  max_output: 50000
  # both tokens only important for character based encoding (word based False)
  start_token: "\t"
  end_token: "\n"
model_training:
  train: False
  model: "distilbert-base-uncased"
  epochs: 10
  # save model weights every save_epochs iterations
  save_epochs: 5
  learning_rate: 0.00001
  batch_size: 64
  num_neurons: 512
load_model:
  folder: "distilbert-base-uncased_2023-11-21_15-30"
  epoch: 5