preprocessing:
  folders: ["SimulatedData2"]
  lower_case: True
  min_words: 1
  mask_symbol: "\r"
encoding:
  word_based: False
  # if word_based True maximal number of words per statement,
  # otherwise maximal number of characters
  max_seq_len: 20
  start_token: "\t"
  end_token: "\n"
model_training:
  train: True
  model: "CharToCharLSTM"
  epochs: 100
  save_epochs: 100
  learning_rate: 0.1
  batch_size: 64
  num_neurons: 7
  validation_split: 0.1
load_model:
  folder: "CharToCharLSTM_2023-11-08_13-12"
  epoch: 50